title: CPT-363
author:
  name: Some Name
  email: 'somename@somewhere.com'
metadata:
    description: 'A short description of your course would go here'
menu:
    - text: Grav
      icon: arrow-circle-right
      url: http://getgrav.org/
github:
    enabled: true
    tree: https://github.com/hibbitts-design/grav-skeleton-bootstrap-course-companion-prototype/edit/master/user/
icon:
    preparations: check-circle
    posts: calendar-o
# The below are required settings for the base theme, and should not be modified
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /redirect-test: /
  '/old/(.*)': /new/$1
routes:
  /something/else: /blog/sample-3
  '/new/(.*)': /blog/$1
blog:
  route: /blog
